<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    
    'О ЗАБЕГЕ'=>'About the race',
    'Миссия'=>'Mission',
    'Медиа центр'=>'Media center',
    'Партнерам'=>'Partners',
    'УЧАСТНИКУ'=>'Participants',
    'Тренировки'=>'Workouts',
    'Список участников'=>'List of participants',
    'Результаты забега'=>'The results of the race',
    'ИНКЛЮЗИЯ'=>'Inclusion',
    'Об Аутизме'=>'About Autism',
    'Лекции'=>'Lectures',
    'Мастер классы'=>'Master classes',
    'Культура'=>'Culture',
    'Фильмы'=>'Films',
    'Онлайн концерт'=>'Online concert',
    'ПРОГРАММА'=>'Program',
    'ВОЛОНТЕРЫ'=>'Volunteers',
    'LIVE'=>'Live',
    'Мой кабинет'=>'PERSONAL CABINET',
    'Введите свой E-mail, чтобы авторизоваться.'=>'Enter your email address to log in.',
    'Если это ваш первый вход, мы вас зарегистрируем.'=>'If this is your first visit, we will register you.',
    'Отправить код'=>'SEND A CODE',
    'Или войдите через'=>'OR LOG IN USING YOUR',
    'Телефон'=>'PHONE',
    'Перейти в кабинет'=>'Kabinetga o‘tish',
    'Выйти'=>'Log out',
    'ВОЙТИ'=>'LOG IN',
    'Войти'=>'Log in',
    'Кабинет'=>'Cabinet',
    '1 ноября 2020'=>'November 1, 2020',
    'ДИСТАНЦИИ'=>'Distances',
    'СУМ'=>'UZS',
    'ЗАРЕГИСТРИРОВАТЬСЯ'=>'REGISTER',
    'СКОРО'=>'COMING SOON',
    'ОНЛАЙН-ЛЕКЦИИ'=>'ONLINE LECTURES',
    'Онлайн-лекции для родителей детей с аутизмом'=>'Online lectures for parents of children with autism',
    'МАСТЕР-КЛАССЫ'=>'MASTER CLASSES',
    'Детские мастер-классы для детей с аутизмом'=>'Children\'s workshops for children with autism',
    'С нами бегут'=>'They run with us',
    'Все участники'=>'All participants',
    'Организаторы'=>'Organizers',
    'Генеральные партнеры'=>'General partners',
    'Партнеры события'=>'Partners of the event',
    'Информационные партнеры'=>'Media partners',
    'Осталось до забега'=>'Left until the race',
    'Дней'=>'Days',
    'Часов'=>'Hours',
    'Минут'=>'Minutes',
    'Секунд'=>'Seconds',
    'Прими участие в полумарафоне прямо сейчас!'=>'Take part in the Half Marathon right now!',
    'Регистрация'=>'Register now',
////////
    'ФОНД РАЗВИТИЯ КУЛЬТУРЫ И ИССКУСТВА'=>'The Art and Culture Development Foundation',
    'ПРИ МИНИСТЕРСТВЕ КУЛЬТУРЫ РУЗ'=>'under the Ministry of Culture of the Republic of Uzbekistan.',
    'АДРЕС'=>'Address',
    '100029 ул. Тараса Шевченко, дом 1.'=>'1 Taras Shevchenko Str., Mirabad district, Tashkent, Uzbekistan, 100029',
    'Рег.'=>'Reg.',
    'ИНН'=>'TIN',
    'ЭЛЕКТРОННАЯ ПОЧТА'=>'E-MAIL',
    'ТЕЛЕФОНЫ'=>'PHONE NUMBERS',
    'по будним дням'=>'on weekdays',
    'СЛЕДИ ЗА СОБЫТИЯМИ'=>'KEEP TRACK OF EVENTS',
    'В НАШИХ СОЦИАЛЬНЫХ СЕТЯХ'=>'IN OUR SOCIAL NETWORKS',
    'ДОСТУПНЫЕ СИСТЕМЫ ОПЛАТЫ'=>'AVAILABLE PAYMENT SYSTEMS',

    '1.Моя анкета'=>'1.MY PROFILE',
    '2.Оплата'=>'2.PAYMENT',
    '3.Подтверждение'=>'3.CONFIRMATION',
    'Ознакомиться с правилами проведения забега'=>'READ THE RULES OF THE RACE',
    'Мой стартовый взнос'=>'MY ENTRY FEE',
    'О мероприятии'=>'ABOUT THE EVENT',
    'Забег'=>'RACE',
    'Дистанция'=>'DISTANCE',
    'Дата старта'=>'START DATE',
    'Место'=>'LOCATION',
    'Время'=>'TIME',
    'Выбранные опции'=>'SELECTED OPTIONS',
    'Пока ничего не выбрано'=>'NOTHING SELECTED YET',
    'Способ оплаты'=>'PAYMENT METHOD',
    'Назад'=>'Back',
    'Начальный взнос'=>'ENTRY FEE',
    'Доставка'=>'DELIVERY',
    'ДОСТАВКА'=>'DELIVERY',
    'Благотворительный взнос'=>'CHARITABLE DONATION',
    'Ура! Вы успешно<br> зарегистрированы<br> на Samarkand<br> Half Marathon!'=>'HOORAY! YOU HAVE BEEN<br> SUCCESSFULLY REGISTERED <br>FOR THE SAMARKAND HALF MARATHON!',
    'Перейти в личный кабинет'=>'GO TO YOUR PERSONAL PROFILE',
    'Моя анкета'=>'MY PROFILE',
    'Мои забеги'=>'MY RACES',
    'Онлайн забег'=>'Online race',
    'Сохранить'=>'Save',
    'Мои фотографии'=>'My photos',
    'Мои сертификаты'=>'My certificates',
    'ВЫБЕРИТЕ КЛУБ...'=>'Choose a club...',
    'ЛАТИНСКИМИ БУКВАМИ'=>'',
    'ВЫБЕРИТЕ ПОЛ...'=>'SELECT GENDER...',
    'МУЖСКОЙ'=>'MALE',
    'ЖЕНСКИЙ'=>'FEMALE',
    'Мобильный телефон'=>'Phone number',
    'Тип авторизации'=>'Auth type',
    'Имя'=>'NAME',
    'Фамилия'=>'LAST NAME',
    'Дата рождения'=>'DATE OF BIRTH',
    'Пол'=>'GENDER',
    'Страна'=>'COUNTRY',
    'Город'=>'CITY',
    'Экстренный контакт'=>'EMERGENCY CONTACT',
    'Размер футболки'=>'T-SHIRT SIZE',
    'Клуб, компания (при наличии)'=>'CLUB, COMPANY (IF AVAILABLE)',
    'АВТОРИЗУЙТЕСЬ с помощью STRAVA'=>'LOG IN WITH STRAVA',
    'Если у вас есть аккаунт в STRAVA – авторизуйтесь. Если аккаунта нет, то зарегистрируйтесь в приложении.'=>'If you have a STRAVA account, please log in. If you don\'t have an account, then register in the app.',
    'Для того, чтобы всё работало правильно, вам необходимо установить<br>на свой смартфон приложение Strava<br>или подключить свои спортивные часы к данному приложению.<br>Убедитесь, что в настройках приватности вы разрешили просматривать<br>ваши тренировки всем пользователям.'=>'In order to make everything work correctly, you need to install the Strava app on your smartphone or connect your sports watch to this app. <br>Make sure that you allow all users to view your training sessions in your privacy settings.',
    'СУМ'=>'UZS',
    'Сум'=>'UZS',
    'Отметьте, если у вас есть официально подтвержденная инвалидность и вы планируете бежать'=>'Mark if you have an officially confirmed disability and you plan to run',
    'Отметьте, если у вас есть необходимость в сопровождающем при вашей форме инвалидности и нужны специальные условия'=>'Mark if you need an accompanying person for your disability form and need special conditions',
    'Я осознаю, что в результате участия могут наступить неблагоприятные последствия для здоровья. Я подтверждаю, что я нахожусь в хорошей физической форме и достаточно подготовлен для участия в данном соревновании и мое физическое состояние было подтверждено лицензированным врачом. <br><br>При несчастном случае или получении любого физического ущерба, которые могут возникнуть во время моего участия в забеге и после него, я добровольно отказываюсь от каких-либо материальных и иных компенсаций и требовании к агентам, сотрудникам, должностным лицам, директорам, преемникам, правопреемникам, спонсорам, поставщикам и иным представителям забега «Samarkand Half Marathon», который состоится с 1 ноября 2020 года по 1 декабря 2020 года. Данный отказ от претензий распространяется на меня, моих родственников, исполнителей, личных представителей, преемников и правопреемников.'=>'I am aware that there may be adverse health consequences as a result of participation. I confirm that I am in good physical condition and sufficiently prepared to participate in this competition and that my physical condition has been confirmed by a licensed doctor. <br><br>In the event of an accident or any physical damage that may occur during my participation in the race and after it, I voluntarily waive any material or other compensation and claim to the agents, employees, officers, directors, successors, assigns, sponsors, suppliers and other representatives of the race "Samarkand Half Marathon", which will be held from November 1, 2020 to December 1, 2020. This disclaimer applies to me, my relatives, performers, personal representatives, successors and assigns.',
    'Перейти к оплате'=>'PROCEED TO PAYMENT',
    'Футболка'=>'T-shirt',
    'Medal'=>'Medal',
    'Bag'=>'Bag',
    'Bottle'=>'Bottle',  
    'Промокод (при наличии)'=>'PROMO CODE (IF AVAILABLE)',
    'Инвалидность'=>'DISABILITY',
    'Связаться со мной'=>'CONTACT ME',
    'Согласен с правилами'=>'I AGREE WITH THE RULES',
    'Введите свой E-mail, чтобы войти в личный кабинет.<br>Если это ваш первый вход, мы создадим для вас личный кабинет.'=>'Enter your email address to log in to your personal account.<br>If this is your first login, we will create a personal account for you.',
    'Введите свой номер телефона, чтобы войти в личный кабинет.<br>Если это ваш первый вход, мы создадим для вас личный кабинет.'=>'Enter your phone number to log in to your personal account.<br>If this is your first login, we will create a personal account for you.',
    'Авторизация'=>'AUTHORIZATION',
    'Личный кабинет'=>'Personal account',
    'На ваш E-mail был отправлен код, пожалуйста введите его.'=>'Code was sent to your email address, please enter it.',
    'На ваш номер телефона был отправлен код, пожалуйста введите его.'=>'Code was sent to your phone number, please enter it.',
    'Получить код повторно'=>'GET THE CODE AGAIN',
    'Будет доступно через  секунд '=>'It will be available after ',
    ' секунд'=>' seconds',

/////////////
    'Международный благотворительный забег в Узбекистане'=>'International charity race in Uzbekistan.',
    'Samarkand Half Marathon – ежегодный благотворительный забег, организованный Фондом развития культуры и искусства при Министерстве культуры Республики Узбекистан совместно с Министерством культуры и Государственным комитетом по развитию туризма Республики Узбекистан, а также хокимиятом Самаркандской области. Проведение благотворительного забега помогает решить задачи по привлечению внимания общественности к проблеме инклюзивности на объектах культуры и искусства, популяризации здорового образа жизни и развитию спортивного туризма в нашей стране.'=>'Samarkand Half Marathon is an annual charity run organized by the Art and Culture Development Foundation under the Ministry of Culture of the Republic of Uzbekistan jointly with the Ministry of Culture and the State Committee for Tourism Development of the Republic of Uzbekistan, as well as Khokimiyat of Samarkand region. Organizing a charity race helps to solve the problems of attracting public attention to the problem of inclusivity in cultural and art objects, promoting a healthy lifestyle and developing sports tourism in our country.',
    'В фокусе организаторов в этом году – возможности людей с расстройством аутистического спектра (РАС) и проблема доступа людей с особенностями развития к объектам культуры и искусства. В рамках мероприятия будут рассмотрены вопросы о создании инклюзивной среды для людей с аутизмом и возможности их интеграции в социальную, культурную и общественную жизнь нашей страны. Средства, вырученные с проведения Samarkand Half Marathon, будут направлены на создание детской художественной студии в одном из интернатов Узбекистана для детей с аутизмом.'=>'This year\'s organizers will focus on the opportunities of people with autism spectrum disorders (ASD) and the problem of access of people with special needs to cultural and art objects. The event will address issues of creating an inclusive environment for people with autism and the possibility of their integration into the social, cultural and public life of our country. The funds raised from the Samarkand Half Marathon will be used to create a children\'s art studio in one of the boarding schools in Uzbekistan for children with autism.',
    'В связи со сложной эпидемиологической обстановкой в мире, программа Samarkand Half Marathon в 2020 году подразумевает проведение спортивной части мероприятия в формате виртуального забега. Формат виртуального забега предоставит участникам Полумарафона свободу выбора локации и дистанции, а результаты будут приниматься по данным, зафиксированным в приложении Strava. Старт благотворительному забегу будет дан 1 ноября. В программу Полумарафона добавлены соревнования по скандинавской ходьбе, а дети до 12 лет пробегут в зачёте отдельного Детского забега. '=>'Due to the complex epidemiological situation in the world, the sports program of the Samarkand Half Marathon in 2020 will be held as a virtual race. The virtual race format will give the participants of the Half Marathon the freedom to choose the location and distance, and the results will be accepted according to the data recorded in the Strava app. The charity race will start on November 1. Nordic walking competitions have been added to the Half Marathon program, and children under 12 will run in a separate Kids\' race.',
    'Образовательная и культурная программы в рамках Самаркандского полумарафона пройдут в диджитал-формате. Представители благотворительной организации National Autistic Society (Великобритания) проведут онлайн-лекции для родителей детей с аутизмом, а специалисты из Британского музея подробно расскажут об их инициативе Early Morning Explorers. При поддержке проекта «Дружелюбная среда» (Россия) будет организована серия   онлайн-дискуссий, вебинаров и мастер-классов. На нашем сайте будет представлена кинопрограмма, разработанная совместно с The Beat Film Festival.'=>'Educational and cultural programs within the framework of the Samarkand Half Marathon will be held in digital format. Representatives of the charity National Autistic Society (UK) will hold online lectures for parents of children with autism, and experts from the British Museum will tell in detail about their Early Morning Explorers initiative. A series of online discussions, webinars and master classes will be organized with the support of the "Friendly environment" project (Russia). Our website will feature a film program developed in conjunction with the Beat Film Festival.',
    'Страница разрабатывается'=>'This page is being developed',
    'Эта страница на данный момент разрабатывается. Попробуйте посетить данную страницу позже.'=>'This page is currently under development. Try visiting this page later.',

////////// 
    'Что такое аутизм?'=>'What is autism?', ////////////
    'Аутизм – это особенность развития, также известная как РАС (расстройство аутистического спектра). Согласно статистике ВОЗ (Всемирная организация здравоохранения) аутизм есть у каждого 160-го ребенка в мире. Распространенность аутизма в различных странах мира одинакова, вне зависимости от географических, этнических, культурных и социально-экономических факторов. А статистические различия могут быть связаны с применяемыми диагностическими методами, диагностическими критериями, а также уровнем осведомленности о РАС».'=>'Autism is a developmental disorder also known as ASD (autism spectrum disorder). According to WHO (World Health Organization) statistics, one in 160 children in the world has autism. The prevalence of autism in different countries of the world is similar, regardless of geographical, ethnic, cultural, and socio-economic factors. Statistical differences may be related to the diagnostic methods used, diagnostic criteria, as well as the level of awareness of ASD.',


    'Аутизм –  это не болезнь. Главное отличие болезни от расстройства в том, что у болезни есть начало, период протекания и конец. Но сегодня в науке доминирует мнение о том, что аутизм появляется из-за генетических причин, а значит, есть у ребенка с самого рождения. Аутизмом нельзя заболеть или заразиться от кого-то. Поэтому корректно называть аутизм не болезнью, а расстройством развития.'=>'Autism is not a disease. The main difference between a disease and a disorder is that a disease has a beginning, continues for a duration of time as an illness, and comes to an end. But today, the dominant view in science is that autism appears to stem from genetic causes, which means that a child has it at birth. You can\'t get autism or get it from someone else. Therefore, it is correctly to refer to autism not as a disease, but as a developmental disorder.',


    'Как понять что перед вами человек  с РАС? Внешне аутизм не заметен, выявить его можно только по результатам поведенческого наблюдения, более того, заметить диагноз зачастую почти невозможно до возраста социального взаимодействия.'=>'How can one detect a person with ASD? Outwardly, autism is not noticeable; it can only be detected by the results of behavioral surveillance. Moreover, it is often almost impossible to notice the diagnosis before the age of social interaction.',


    'Проявления расстройства крайне разнообразны. Люди в спектре аутизма всегда имеют проблему с коммуникацией, часто не разговаривают совсем, могут порой плохо понимать, что вы им говорите или с трудом распознавать разные проявления эмоций, а также иронию, юмор, использование слов в переносном значении. Но есть также категория людей, которые с удовольствием находятся в постоянном контакте с окружающими.'=>'Manifestations of the disorder are extremely diverse. People on the autism spectrum have problems with communication, some do not speak at all, sometimes they have a poor understanding of what you are saying to them, or they have difficulty recognizing different expressions of emotions like irony, humor, and the use of words in a figurative sense. But there is also a category of people who are happy to be in regular contact with others.',


    'Жизнь с таким расстройством часто подчиняется заведённому распорядку, отступление от которого переносится крайне болезненно. Любые перемены приносят в замкнутую жизнь людей с аутизмом стресс и раздражение.'=>'Life with such a disorder is often subject to a routine, deviation from which is extremely painful. Any changes cause stress and irritation in the sheltered lives of people with autism.',


    'Сегодня единственный действенный метод помощи детям с аутизмом – это коррекционное обучение. Оно способно помочь выстроить коммуникацию и пробудить интерес к учёбе и освоению новых навыков.'=>'Today, the only effective method of helping children with autism is remedial education. It helps to build a communication network and arouse interest in studying and learning new skills.',


    'РАС – не просто медицинский термин, но и важное слово в борьбе за инклюзивную среду. Сам принцип инклюзивности возник во многом благодаря усилиям Лорны Уинг и британского Национального аутистического общества. С 60-х годов они требовали пересмотреть систему образования, включив туда людей с расстройствами аутистического спектра, тогда как государства Западной Европы отказывались от социальных пособий и адресной помощи. '=>'ASD is not just a medical term, but also an important word in the fight for an inclusive environment. The principle of inclusivity itself originated mainly through the efforts of Lorna Wing and the British National Autistic Society. Since the 60s, they have been demanding a review of the education system in order to include people with autism spectrum disorders, while Western European countries have been refusing social benefits and targeted assistance.',


    'В Узбекистане аутизм был включён в список психических заболеваний в 2010 году. По некоторым данным в Республиканском центре социальной адаптации детей (РЦСАД) зарегистрировано около 400 детей с аутизмом, большая часть которых проживает в Ташкенте и Ташкентской области. Однако, родители детей с РАС утверждают, что семей, столкнувшихся с аутизмом гораздо больше. Также до сих пор существуют трудности в диагностике расстройств аутистического спектра. В силу отсутствия всестороннего понимания проблемы часто происходит некорректная интерпретация клинических проявлений того или иного состояния и в итоге специфические трудности в обучении рассматриваются в качестве психиатрической патологии. '=>'In Uzbekistan, autism was included in the list of mental illnesses in 2010. According to some data, the Republican Center for the Social Adaptation of Children (RCSAD) registered about 400 children with autism, most of whom live in Tashkent and the Tashkent region. However, parents of children with ASD claim that there are many more families affected by autism in them. There are also still difficulties in diagnosing autism spectrum disorders. Due to the lack of a comprehensive understanding of the problem, the incorrect interpretation of the clinical manifestations of a particular condition often occurs, and as a result specific learning difficulties are considered as psychiatric pathology.',
////////////////














    'Другая сумма'=>'OTHER AMOUNT',
    'Забрать в месте выдачи (Ташкент) 0 сум'=>'PICK UP AT THE PLACE OF ISSUE (TASHKENT) 0 UZS',
    'По Узбекистану (кроме Ташкента) 20 000 сум'=>'WITHIN UZBEKISTAN (EXCEPT TASHKENT) 20,000 UZS',
    'По странам СНГ 72 000 сум'=>'FOR CIS COUNTRIES 72,000 UZS',
    'Дальнее зарубежье (оплата при получении)'=>'FAR ABROAD (PAYMENT UPON RECEIPT)',
    'ПОДЕЛИСЬ ЭТОЙ НОВОСТЬЮ СО СВОИМИ ДРУЗЬЯМИ'=>'SHARE THIS NEWS WITH YOUR FRIENDS',
    'Вы уже успешно зарегистрированы на Samarkand Half Marathon!'=>'YOU HAVE BEEN SUCCESSFULLY REGISTERED FOR THE SAMARKAND HALF MARATHON!',
    'Перейти в личный кабинет'=>'GO TO YOUR PERSONAL PROFILE',
    'Все средства, полученные с благотворительных взносов, будут направлены в фонд благотворительности Узбекистана'=>'All funds received from charitable donations will be directed to the charity foundation of Uzbekistan',


    'Неправильный код. Попробуйте снова.'=>'Invalid code. Try again.',
    '+ ДОБАВИТЬ СВОЙ'=>'+ ADD YOUR OWN',
    'Введите название вашего клуба'=>'Enter the name of your club',
    'ВЫБЕРИТЕ СТРАНУ...'=>'SELECT A COUNTRY',
    'ВЫБЕРИТЕ СПЕРВА СТРАНУ...'=>'SELECT YOUR COUNTRY FIRST',
    'Выберите дистанцию'=>'Select a distance',
    'ДОБАВЬ К СОБЫТИЮ УНИКАЛЬНУЮ МЕДАЛЬ, ФУТБОЛКУ <br> ИЛИ ВЕСЬ КОМПЛЕКТ'=>'ADD A UNIQUE MEDAL AND T-SHIRT TO THE EVENT<br>OR THE FULL SET',
    'ВЫБРАТЬ'=>'SELECT',
    'ВЫБРАНО'=>'SELECTED',
    'Адрес доставки'=>'Delivery address',
    'АДРЕС ДОСТАВКИ'=>'DELIVERY ADDRESS',
    'Место проведения'=>'Place of the event',
    'Время старта'=>'Start time',
    'Загрузить скриншоты'=>'Upload screenshots',
    'Промокод'=>'Promocode',

    '26 сентября 12:00'=>'September 26, 12:00 AM',
    '«ЧТО ТАКОЕ АУТИЗМ?»'=>'“WHAT IS AUTISM?”',
    'Александра Петрова, менеджер программы «Аутизм.<br>Дружелюбная среда» благотворительного фонда «Выход»'=>'Alexandra Petrova, ”Autism. Friendly environment"<br> program manager of the Charity Foundation "A Way Out"',
    'ПЕРЕЙТИ'=>'GO',
    'мин' => 'min',

    '16 октября 18:00'=>'16 october 18:00',
    '«Аутизм. Дружелюбная среда»'=>'“Autism. Friendly environment”',
    'Александра Петрова (проект «Аутизм. Дружелюбная среда») и Елена Шарова (Музей русского импрессионизма)'=>'Aleksandra Petrova (“Autism. Friendly environment” project) and Elena Sharova (Rusian impressionism museum)',

    '(Онлайн забег с ипользованием GPS приложения Strava)'=>'(Online race with the Strava GPS app)',
    '(Онлайн ходьба с палками, также известная как Скандинавская ходьба)'=>'(Online walking with sticks)',
    '(Онлайн забег на 1 км для детей до 12 лет)'=>'(Online 1km race for children under the age of 12)',

    'Здесь будут отображаться ваши тренировки после загрузки на Strava.'=>'This is where your workouts will be displayed after you download Strava.',
    'Пока здесь пусто. Информация будет доступна 1 ноября.'=>'It\'s empty for now. The information will be available on November 1.',


    'Октябрь 23, 2020 – Октябрь 25, 2020' => 'October 23, 2020 - October 25, 2020',
    'ТАЙВАНЬ | 2019 | ДОКУМЕНТАЛЬНЫЙ ФИЛЬМ | 102 мин' => 'TAIWAN | 2019 | DOCUMENTARY FILM | 102 min',
    'Бег За Мечтой' => 'Run For Dream',

    'Успешно подключено'=>'Successfully connected',
    'Требуется подключение'=>'Connection required',
    'Перейти в кабинет'=>'Cabinet',
    'ДИСЦИПЛИНА'=>'Discipline',
    'МАГАЗИН'=>'Shop',

    //'РЕЖИССЁР: Мао-Сен Хуан<br>ПРОДЮССЕР: Шу-Ю Лин<br>Представленно B\'tween<br><br>ОБЗОР<br><br>Йен-По Чен (Томми Чен) – известный тайваньский ультрамарафонист, который стал первым в истории азиатским спортсменом, завершившим серию 4 Deserts Race Series и завоевавшим титул чемпиона мира в 2016 году. В документальном фильме «Бег за мечтой» рассказана история о захватывающем и опасном десятилетнем путешествии Чен Йен-По на пути к чемпионству. Съемочная команда смогла заснять часть путешествия Чена по миру. В течение шести месяцев они ездили по пустыням поднимались в горы и бороздили снежные поля; они дошли до Северного Ледовитого океана и Антарктиды. Фильм позволяет зрителям стать свидетелями крови, пота и слез Чена, а также его непоколебимой настойчивости. Это путешествие, наполненное любовью и поддержкой родных и друзей, и даже соперников, которые проявили братскую заботу, сделав этот путь к успеху более приятным.' => 'REJISSYOR: Mao-Sen Xuan <br> PRODYUSSER: Shu-Yu Lin<br> B\'tween taqdim qilingan<br><br>UMUMIY SHARH<br><br>Yen-Po Chen (Tommy Chen) - Tayvanlik taniqli ul\'tramarafon yuguruvchisi, u 4-cho‘llar poygasi seriyasini yakunlagan va 2016 yilda jahon chempioni bo‘lgan birinchi Osiyo sportchisi bo‘ldi. "Orzu uchun yugur" hujjatli fil\'mida Chen Yen-Poning chempionlik tomon o‘n yillik hayajonli va xavfli sayohati haqida hikoya qilinadi. Suratga olish guruhi Chenning dunyo bo‘ylab sayohatining bir qismini suratga olishga muvaffaq bo‘ldi. Olti oy davomida ular cho‘llar bo‘ylab yurishdi, tog‘larga chiqishdi va mo‘ynali qor maydonlariga; Shimoliy Muz okeaniga va Antarktidaga yetib kelishdi. Fil\'m tomoshabinlarga Chenning qoni, terlari va ko‘z yoshlari hamda uning mustahkam qat\'iyatiga guvoh bo‘lishiga imkon beradi. Bu safar oilangiz va do‘stlaringizning sevgisi va ko‘magi bilan, hatto birodarlik g‘amxo‘rligini ko‘rsatgan raqiblari bilan muvaffaqiyatga erishish yo‘lini yanada yoqimli qilish bilan to‘lgan sayohatdir.',


];
